"""initial schema

Revision ID: 38a0e7c60c76
Revises: 
Create Date: 2026-04-28 19:05:00.041066
"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '38a0e7c60c76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oparl_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bodies_oparl_id'), 'bodies', ['oparl_id'], unique=True)
    op.create_table('crawl_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('objects_fetched', sa.Integer(), nullable=False),
    sa.Column('objects_new', sa.Integer(), nullable=False),
    sa.Column('objects_updated', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_oparl_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oparl_id', sa.String(), nullable=False),
    sa.Column('oparl_type', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_oparl_objects_oparl_id'), 'raw_oparl_objects', ['oparl_id'], unique=True)
    op.create_index(op.f('ix_raw_oparl_objects_oparl_type'), 'raw_oparl_objects', ['oparl_type'], unique=False)
    op.create_index('ix_raw_oparl_type_fetched', 'raw_oparl_objects', ['oparl_type', 'fetched_at'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oparl_id', sa.String(), nullable=False),
    sa.Column('body_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('meeting_state', sa.String(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['bodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_body_id'), 'meetings', ['body_id'], unique=False)
    op.create_index(op.f('ix_meetings_oparl_id'), 'meetings', ['oparl_id'], unique=True)
    op.create_index('ix_meetings_start', 'meetings', ['start'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oparl_id', sa.String(), nullable=False),
    sa.Column('body_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('organization_type', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['bodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_body_id'), 'organizations', ['body_id'], unique=False)
    op.create_index(op.f('ix_organizations_oparl_id'), 'organizations', ['oparl_id'], unique=True)
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oparl_id', sa.String(), nullable=False),
    sa.Column('body_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('paper_type', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('main_file_url', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['bodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_body_id'), 'papers', ['body_id'], unique=False)
    op.create_index(op.f('ix_papers_date'), 'papers', ['date'], unique=False)
    op.create_index(op.f('ix_papers_oparl_id'), 'papers', ['oparl_id'], unique=True)
    op.create_index(op.f('ix_papers_paper_type'), 'papers', ['paper_type'], unique=False)
    op.create_index(op.f('ix_papers_reference'), 'papers', ['reference'], unique=False)
    op.create_index('ix_papers_search_vector', 'papers', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oparl_id', sa.String(), nullable=False),
    sa.Column('body_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('form_of_address', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['body_id'], ['bodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_body_id'), 'persons', ['body_id'], unique=False)
    op.create_index(op.f('ix_persons_oparl_id'), 'persons', ['oparl_id'], unique=True)
    op.create_table('agenda_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oparl_id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('resolution_text', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_items_meeting_id'), 'agenda_items', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_agenda_items_oparl_id'), 'agenda_items', ['oparl_id'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oparl_id', sa.String(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('access_url', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_oparl_id'), 'files', ['oparl_id'], unique=True)
    op.create_index(op.f('ix_files_paper_id'), 'files', ['paper_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oparl_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberships_oparl_id'), 'memberships', ['oparl_id'], unique=True)
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_person_id'), 'memberships', ['person_id'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oparl_id', sa.String(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('authoritative', sa.Boolean(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_agenda_item_id'), 'consultations', ['agenda_item_id'], unique=False)
    op.create_index(op.f('ix_consultations_oparl_id'), 'consultations', ['oparl_id'], unique=True)
    op.create_index(op.f('ix_consultations_paper_id'), 'consultations', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultations_paper_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_oparl_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_agenda_item_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_memberships_person_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_oparl_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_files_paper_id'), table_name='files')
    op.drop_index(op.f('ix_files_oparl_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_agenda_items_oparl_id'), table_name='agenda_items')
    op.drop_index(op.f('ix_agenda_items_meeting_id'), table_name='agenda_items')
    op.drop_table('agenda_items')
    op.drop_index(op.f('ix_persons_oparl_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_body_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index('ix_papers_search_vector', table_name='papers', postgresql_using='gin')
    op.drop_index(op.f('ix_papers_reference'), table_name='papers')
    op.drop_index(op.f('ix_papers_paper_type'), table_name='papers')
    op.drop_index(op.f('ix_papers_oparl_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_date'), table_name='papers')
    op.drop_index(op.f('ix_papers_body_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_organizations_oparl_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_body_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_meetings_start', table_name='meetings')
    op.drop_index(op.f('ix_meetings_oparl_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_body_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index('ix_raw_oparl_type_fetched', table_name='raw_oparl_objects')
    op.drop_index(op.f('ix_raw_oparl_objects_oparl_type'), table_name='raw_oparl_objects')
    op.drop_index(op.f('ix_raw_oparl_objects_oparl_id'), table_name='raw_oparl_objects')
    op.drop_table('raw_oparl_objects')
    op.drop_table('crawl_log')
    op.drop_index(op.f('ix_bodies_oparl_id'), table_name='bodies')
    op.drop_table('bodies')
    # ### end Alembic commands ###
