"""add tenders table

Revision ID: 975f6718a58f
Revises: b310be8bc0db
Create Date: 2026-04-29 17:25:25.140094
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '975f6718a58f'
down_revision: Union[str, None] = 'b310be8bc0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contracting_authority', sa.String(), nullable=True),
    sa.Column('tender_type', sa.String(), nullable=True),
    sa.Column('procedure_type', sa.String(), nullable=True),
    sa.Column('cpv_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('awarded_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('award_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenders_authority_date', 'tenders', ['contracting_authority', 'publication_date'], unique=False)
    op.create_index(op.f('ix_tenders_contracting_authority'), 'tenders', ['contracting_authority'], unique=False)
    op.create_index(op.f('ix_tenders_publication_date'), 'tenders', ['publication_date'], unique=False)
    op.create_index(op.f('ix_tenders_source'), 'tenders', ['source'], unique=False)
    op.create_index(op.f('ix_tenders_source_id'), 'tenders', ['source_id'], unique=True)
    op.create_index(op.f('ix_tenders_tender_type'), 'tenders', ['tender_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_tender_type'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_source_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_source'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_publication_date'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_contracting_authority'), table_name='tenders')
    op.drop_index('ix_tenders_authority_date', table_name='tenders')
    op.drop_table('tenders')
    # ### end Alembic commands ###
