"""add pardok tables

Revision ID: a92efc858bf8
Revises: 975f6718a58f
Create Date: 2026-04-29 21:35:52.852744
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a92efc858bf8'
down_revision: Union[str, None] = '975f6718a58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pardok_vorgaenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorgang_id', sa.String(), nullable=False),
    sa.Column('vorgang_typ', sa.String(), nullable=True),
    sa.Column('systematik', sa.String(), nullable=True),
    sa.Column('systematik_label', sa.String(), nullable=True),
    sa.Column('wahlperiode', sa.Integer(), nullable=True),
    sa.Column('deskriptoren', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_fhk', sa.Boolean(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pardok_vorgaenge_is_fhk'), 'pardok_vorgaenge', ['is_fhk'], unique=False)
    op.create_index(op.f('ix_pardok_vorgaenge_systematik'), 'pardok_vorgaenge', ['systematik'], unique=False)
    op.create_index(op.f('ix_pardok_vorgaenge_vorgang_id'), 'pardok_vorgaenge', ['vorgang_id'], unique=True)
    op.create_index(op.f('ix_pardok_vorgaenge_vorgang_typ'), 'pardok_vorgaenge', ['vorgang_typ'], unique=False)
    op.create_table('pardok_dokumente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dokument_id', sa.String(), nullable=False),
    sa.Column('vorgang_id', sa.Integer(), nullable=False),
    sa.Column('dok_art', sa.String(), nullable=True),
    sa.Column('dok_typ', sa.String(), nullable=True),
    sa.Column('dok_nr', sa.String(), nullable=True),
    sa.Column('titel', sa.String(), nullable=True),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('urheber', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['vorgang_id'], ['pardok_vorgaenge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pardok_dokumente_datum'), 'pardok_dokumente', ['datum'], unique=False)
    op.create_index(op.f('ix_pardok_dokumente_dok_art'), 'pardok_dokumente', ['dok_art'], unique=False)
    op.create_index(op.f('ix_pardok_dokumente_dok_nr'), 'pardok_dokumente', ['dok_nr'], unique=False)
    op.create_index(op.f('ix_pardok_dokumente_dok_typ'), 'pardok_dokumente', ['dok_typ'], unique=False)
    op.create_index(op.f('ix_pardok_dokumente_dokument_id'), 'pardok_dokumente', ['dokument_id'], unique=True)
    op.create_index(op.f('ix_pardok_dokumente_vorgang_id'), 'pardok_dokumente', ['vorgang_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pardok_dokumente_vorgang_id'), table_name='pardok_dokumente')
    op.drop_index(op.f('ix_pardok_dokumente_dokument_id'), table_name='pardok_dokumente')
    op.drop_index(op.f('ix_pardok_dokumente_dok_typ'), table_name='pardok_dokumente')
    op.drop_index(op.f('ix_pardok_dokumente_dok_nr'), table_name='pardok_dokumente')
    op.drop_index(op.f('ix_pardok_dokumente_dok_art'), table_name='pardok_dokumente')
    op.drop_index(op.f('ix_pardok_dokumente_datum'), table_name='pardok_dokumente')
    op.drop_table('pardok_dokumente')
    op.drop_index(op.f('ix_pardok_vorgaenge_vorgang_typ'), table_name='pardok_vorgaenge')
    op.drop_index(op.f('ix_pardok_vorgaenge_vorgang_id'), table_name='pardok_vorgaenge')
    op.drop_index(op.f('ix_pardok_vorgaenge_systematik'), table_name='pardok_vorgaenge')
    op.drop_index(op.f('ix_pardok_vorgaenge_is_fhk'), table_name='pardok_vorgaenge')
    op.drop_table('pardok_vorgaenge')
    # ### end Alembic commands ###
