"""add budget tables

Revision ID: b310be8bc0db
Revises: 38a0e7c60c76
Create Date: 2026-04-29 15:21:10.474152
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b310be8bc0db'
down_revision: Union[str, None] = '38a0e7c60c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('year1', sa.Integer(), nullable=False),
    sa.Column('year2', sa.Integer(), nullable=False),
    sa.Column('kapitel_count', sa.Integer(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_plans_reference'), 'budget_plans', ['reference'], unique=False)
    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('kapitel', sa.String(length=4), nullable=False),
    sa.Column('titel', sa.String(length=5), nullable=False),
    sa.Column('funktion', sa.String(length=3), nullable=False),
    sa.Column('bezeichnung', sa.String(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('kennbuchstabe', sa.String(length=3), nullable=False),
    sa.Column('ansatz_year1', sa.Float(), nullable=True),
    sa.Column('ansatz_year2', sa.Float(), nullable=True),
    sa.Column('ansatz_prev', sa.Float(), nullable=True),
    sa.Column('ist_prev', sa.Float(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('erlaeuterung', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['budget_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_items_kapitel'), 'budget_items', ['kapitel'], unique=False)
    op.create_index('ix_budget_items_kapitel_titel', 'budget_items', ['kapitel', 'titel'], unique=False)
    op.create_index(op.f('ix_budget_items_plan_id'), 'budget_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_budget_items_titel'), 'budget_items', ['titel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_items_titel'), table_name='budget_items')
    op.drop_index(op.f('ix_budget_items_plan_id'), table_name='budget_items')
    op.drop_index('ix_budget_items_kapitel_titel', table_name='budget_items')
    op.drop_index(op.f('ix_budget_items_kapitel'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_budget_plans_reference'), table_name='budget_plans')
    op.drop_table('budget_plans')
    # ### end Alembic commands ###
